// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmMvNFtWJzPzCXAbhhCJ5kqJ7c2AQ7ZSo',
    appId: '1:188401794547:android:379507a2cb032a65ac6686',
    messagingSenderId: '188401794547',
    projectId: 'finstagram-app-66672',
    storageBucket: 'finstagram-app-66672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4khVcUegLT8B5-yDievpZn0qROxxPgco',
    appId: '1:188401794547:ios:041fc04ea0085e21ac6686',
    messagingSenderId: '188401794547',
    projectId: 'finstagram-app-66672',
    storageBucket: 'finstagram-app-66672.firebasestorage.app',
    androidClientId:
        '188401794547-is1q47dt9u0pv806jf687g5k359qsbu9.apps.googleusercontent.com',
    iosClientId:
        '188401794547-nknkj2ljblgdten70elu58in0gfn8bcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.finstagrmApp',
  );
}
